# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies two doubles
#'
#' @param t double
#' @return Product of v1 and v2
RationalApproximation <- function(t) {
    .Call(`_checknormality_RationalApproximation`, t)
}

NormalCDFInverse <- function(p) {
    .Call(`_checknormality_NormalCDFInverse`, p)
}

stl_sort <- function(x) {
    .Call(`_checknormality_stl_sort`, x)
}

C_get_W <- function(vec_value) {
    .Call(`_checknormality_C_get_W`, vec_value)
}

