# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the Rational Approximation
#'
#' This function was taken from https://www.johndcook.com/blog/cpp_phi_inverse/
#'
#'
#' @param t double
#' @return Product of v1 and v2
#'
#' @export
RationalApproximation <- function(t) {
    .Call(`_checknormality_RationalApproximation`, t)
}

#' Calculates the Normal CDF Inverse
#'
#' This function was taken from https://www.johndcook.com/blog/cpp_phi_inverse/
#' @param double p
#' @return value for which the normal CDF < p
#'
#' @export
NormalCDFInverse <- function(p) {
    .Call(`_checknormality_NormalCDFInverse`, p)
}

#' Sorts a vector in ascending order
#'
#' @param NumericVector x
#' @return x in ascending order
#'
#' @export
stl_sort <- function(x) {
    .Call(`_checknormality_stl_sort`, x)
}

#' Calculate the W statistic for the Royston approach (implemented in Rcpp)
#'
#' This function calculates the W test statistic for the Royston approach for
#' the Shapiro-Wilk test. This function is comparable to the R implementation
#' of the Royston approach (which can be found in the R folder). For a
#' step-by-step explanation of this function, look at the Readme file under
#' "A Note on the Algorithms".
#'
#' @param vec_value vector containing data points; integer or double
#' @return the test statistic for the Shapiro-Wilk test; double, between 0 and
#' 1
#'
#' @export
#'
#'
C_get_W <- function(vec_value) {
    .Call(`_checknormality_C_get_W`, vec_value)
}

